# Site settings
title:
email:
author:
description:
url: https://leanbase.io
baseUrl: https://leanbase.io/

# Build settings
include: ['_posts']
permalink: /blog/:title/
sass:
  sass_dir: assets/scss

plugins:
  - jekyll-sitemap

collections:
  - offshore_articles
