# Site settings
url: https://leanbase.io
baseUrl: https://leanbase.io/

# Build settings
permalink: /blog/:title/
sass:
  sass_dir: assets/scss

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

collections:
  - offshore_articles

# SEO Stuff
twitter:
  username: LeanbaseHQ
  card: summary

social:
  name: LeanbaseHQ
  links:
    - https://twitter.com/LeanbaseHQ

logo: /assets/images/logo-with-text-square.png
title: Leanbase | Feature Flagging for Faster Testing and Continous Delivery.
description: Modern product teams are delivering faster by using Feature Flagging practices. Untangle code deployments from feature releases and build better software safely. Use Leanbase to power your feature flags at any scale.
locale: en_US