# Site settings
url: https://leanbase.io
baseUrl: https://leanbase.io/

# Build settings
permalink: /blog/:title/
sass:
  sass_dir: assets/scss

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

collections:
  offshore_articles:
  docs:
    output: true
    permalink: "/:collection/"

# SEO Stuff
twitter:
  username: LeanbaseHQ
  card: summary_large_image

logo: /assets/images/logo-with-text-square.png
title: Leanbase
description: Modern product teams are delivering faster by using Feature Flagging practices. Untangle code deployments from feature releases and build better software safely. Use Leanbase to power your feature flags at any scale.
locale: en_US