steps:
- name: jekyll/jekyll:latest
  entrypoint: bundle
  args: ['install']
  volumes:
  - name: 'bundle_storage'
    path: '/usr/local/bundle'
- name: alpine
  entrypoint: mkdir
  args: ['-p', './_site']
- name: alpine
  entrypoint: chmod
  args: ['777', './_site']
- name: jekyll/jekyll:latest
  entrypoint: bundle
  args: ['exec', 'jekyll', 'build']
  volumes:
  - name: 'bundle_storage'
    path: '/usr/local/bundle'
- name: 'gcr.io/cloud-builders/gsutil'
  entrypoint: gsutil
  args: ['-m', 'rsync', '-r', './_site', 'gs://www.leanbase.io']
options:
  env:
    - 'JEKYLL_VERSION=3.8'