steps:
# First, touch a gemfile so that cloud build can write to it.
- name: 'ubuntu'
  args: ['touch', './Gemfile.lock']
- name: jekyll/jekyll:latest
  env:
    - 'JEKYLL_VERSION=3.8'
  entrypoint: jekyll
  args: ['build']
- name: gcr.io/cloud-builders/gcloud
  entrypoint: gsutil
  args: ["-m", "rsync", "-r", "-c", "-d", "./_site", "gs://example.com"]
- name: 'gcr.io/cloud-builders/gsutil'
  args: ['-m', 'rsync', '-r', './_site', 'gs://www.leanbase.io']