steps:
- name: jekyll/jekyll:latest
  entrypoint: bundle
  args: ['install']
  volumes:
  - name: 'bundle_storage'
    path: '/usr/local/bundle'
- name: jekyll/jekyll:latest
  entrypoint: bundle
  args: ['exec', 'jekyll', 'build']
  volumes:
  - name: 'bundle_storage'
    path: '/usr/local/bundle'
- name: gcr.io/cloud-builders/gcloud
  entrypoint: gsutil
  args: ["-m", "rsync", "-r", "-c", "-d", "./_site", "gs://example.com"]
- name: 'gcr.io/cloud-builders/gsutil'
  args: ['-m', 'rsync', '-r', './_site', 'gs://www.leanbase.io']
options:
  env:
    - 'JEKYLL_VERSION=3.8'